### ISSUE TITLE
NuGet package?

### ISSUE THREAD

**Issue by ignatandrei** [JasonBock/AutoDeconstruct#15]
Hello
I am making a re-make about the Source Code Generators -  https://ignatandrei.github.io/RSCG_Examples/v1/index.docx 
This time I want to include only RSCG that have implemented incremental generators -  see  https://ignatandrei.github.io/RSCG_Examples/v2/

To mention this, I need you to publish a NuGet package . Could you do that ?

Thanks
Andrei

**Comment by JasonBock** [comment]
The package has been there since the repo was made: https://www.nuget.org/packages/AutoDeconstruct
