### ISSUE TITLE
Explicit code generation

### ISSUE THREAD

**Issue by kolpav** [JasonBock/AutoDeconstruct#3]
Hi,

when I reading about source generators generating Deconstruct methods was something I was going to do but gave up because source generators are still kind of pain to work with so I am glad I found your project.

From reading design doc it seems deconstruct methods are generated for every type but I think wanting to generate deconstructs for small selection of types is much more likely scenario. I have few suggestions/questions

1. Does adding this to project with a lot of types like thousands and more suitable for deconstruct methods increase build time by noticeable amount?
2. Wouldn't it be better to invert logic such as instead of having `[NoAutoDeconstruct]` there would be `[AutoDeconstruct]`?
3. Even better detect usages of deconstruction syntax and generate code just for those types? No need for attributes with some rules for order of properties maybe respecting order defined in type or match them by name or some other heuristic.

For type
```cs
public class Foo
{
  public int Id { get; set; }
  public string Boo { get; set; }
}
```
You could have this in your code, respecting order and naming
```cs
var (id, boo) = new Foo();
```
Which would generate:
```cs
public void Deconstruct(out int id, out string boo) => (Id, Boo) = (id, boo);
```
But you could even have
```cs
var (boo, id) = new Foo();
```
Which would generate:
```cs
public void Deconstruct(out string boo, out int id) => (Id, Boo) = (id, boo);
```
because its able to match properties by name. Thats just an idea having attribute for explicit code generation would be enough and make this library much more usable imho. Btw I don't expect you to implement anything I am just curious what you think.

**Comment by JasonBock** [comment]
I appreciate the questions. Just keep in mind that I did this work mostly to see if I **could** do it :). I really haven't put a lot of thought into next steps or anything like that.

If a project has thousands of type definitions, then yes, AutoDeconstruct would create a `Deconstruct()` method whenever it could. Though, keep in mind that the relative size of all these `Deconstruct()` methods should be small compared to the total overall code size of the project. 

I mention at the end of my [design doc](https://github.com/JasonBock/AutoDeconstruct/blob/main/docs/Design.md) that there could be something in place like an attribute to exclude a type from participation. Another option would be some kind of configuration approach to specify types that should not have deconstruction. I really don't have anything concrete in mind right now.

There are potential issues with letting a developer specify that they want a `Deconstruct()` method made by simply typing it into the code. What if the underlying type has 5 properties that could be deconstructed? How do I know which ones I would put in the method signature? Do I force a convention to the user that they have to have their deconstructed variable names match the property names? What if a developer has this:
```
public class Person
{
    public string Name { get; set; }
    public Guid Id { get; set; }
    public int Age { get; set; }
}

var (id, age) = new Person();
var (name, id) = new Person();
```
I can't generate two `Deconstruct()` methods with the same number of parameters. That's not allowed as far as I know.
